name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install and test
        run: |
          yarn --frozen-lockfile
          yarn test
          yarn build

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "ever-teams-399720"

      - name: Replace placeholders with secrets
        run: |
          sed -i 's|PLACEHOLDER_GOOGLE_CREDENTIALS|${{ secrets.GOOGLE_CREDENTIALS }}|g' app.template.yaml
          mv app.template.yaml app.yaml

      - name: "Deploy to GCP AppEngine"
        run: |
          yarn deploy

      # Deploy to App Engine (another way)
      # - name: Deploy to App Engine
      # uses: google-github-actions/deploy-appengine@v1
      #  with:
      #    project_id: ever-teams-399720
      #    deliverables: app.yaml
      #    promote: true
